// All badge definitions — used for auto-award logic and display
export const BADGE_DEFINITIONS = [

  // ── PICKS ────────────────────────────────────────────────────────────────
  {
    key: 'first_pick',
    title: 'Početnik',
    description: 'Sudjeluj u svom prvom natjecanju',
    emoji: '🎯',
    category: 'picks',
    rarity: 'common',
    condition_type: 'picks_count',
    condition_value: 1,
    reward_tokens: 100,
  },
  {
    key: 'picks_10',
    title: 'Redoviti igrač',
    description: 'Sudjeluj u 10 natjecanja',
    emoji: '🃏',
    category: 'picks',
    rarity: 'common',
    condition_type: 'picks_count',
    condition_value: 10,
    reward_tokens: 250,
  },
  {
    key: 'picks_50',
    title: 'Veteran',
    description: 'Sudjeluj u 50 natjecanja',
    emoji: '⚔️',
    category: 'picks',
    rarity: 'rare',
    condition_type: 'picks_count',
    condition_value: 50,
    reward_tokens: 1000,
  },
  {
    key: 'picks_100',
    title: 'Legenda',
    description: 'Sudjeluj u 100 natjecanja',
    emoji: '👑',
    category: 'picks',
    rarity: 'legendary',
    condition_type: 'picks_count',
    condition_value: 100,
    reward_tokens: 5000,
  },
  {
    key: 'picks_200',
    title: 'Besmrtnik',
    description: 'Sudjeluj u 200 natjecanja',
    emoji: '🌌',
    category: 'picks',
    rarity: 'legendary',
    condition_type: 'picks_count',
    condition_value: 200,
    reward_tokens: 10000,
  },

  // ── WINS ─────────────────────────────────────────────────────────────────
  {
    key: 'first_win',
    title: 'Prva pobjeda',
    description: 'Pobijedi u svom prvom natjecanju',
    emoji: '🏆',
    category: 'picks',
    rarity: 'common',
    condition_type: 'wins_count',
    condition_value: 1,
    reward_tokens: 200,
  },
  {
    key: 'wins_5',
    title: 'Na dobrom putu',
    description: 'Osvoji 5 natjecanja',
    emoji: '🌟',
    category: 'picks',
    rarity: 'common',
    condition_type: 'wins_count',
    condition_value: 5,
    reward_tokens: 300,
  },
  {
    key: 'wins_10',
    title: 'Pobjednički mentalitet',
    description: 'Osvoji 10 natjecanja',
    emoji: '🥇',
    category: 'picks',
    rarity: 'rare',
    condition_type: 'wins_count',
    condition_value: 10,
    reward_tokens: 500,
  },
  {
    key: 'wins_25',
    title: 'Top prognozer',
    description: 'Osvoji 25 natjecanja — pravi ekspert za statistiku!',
    emoji: '📊',
    category: 'picks',
    rarity: 'rare',
    condition_type: 'wins_count',
    condition_value: 25,
    reward_tokens: 1500,
  },
  {
    key: 'wins_50',
    title: 'Nepobjedivi',
    description: 'Osvoji 50 natjecanja',
    emoji: '🦁',
    category: 'picks',
    rarity: 'epic',
    condition_type: 'wins_count',
    condition_value: 50,
    reward_tokens: 3000,
  },
  {
    key: 'wins_100',
    title: 'Osvajač',
    description: 'Osvoji 100 natjecanja — vrh platforme!',
    emoji: '🎖️',
    category: 'picks',
    rarity: 'legendary',
    condition_type: 'wins_count',
    condition_value: 100,
    reward_tokens: 8000,
  },

  // ── WIN RATE ─────────────────────────────────────────────────────────────
  {
    key: 'winrate_60',
    title: 'Oštro oko',
    description: 'Postizi win rate od 60%+ (min. 10 igara)',
    emoji: '🎯',
    category: 'picks',
    rarity: 'rare',
    condition_type: 'win_rate_60',
    condition_value: 60,
    reward_tokens: 1000,
  },
  {
    key: 'winrate_70',
    title: 'Snajper',
    description: 'Postizi win rate od 70%+ (min. 20 igara)',
    emoji: '🔭',
    category: 'picks',
    rarity: 'epic',
    condition_type: 'win_rate_70',
    condition_value: 70,
    reward_tokens: 2500,
  },
  {
    key: 'winrate_80',
    title: 'Oracle',
    description: 'Postizi win rate od 80%+ (min. 20 igara) — gotovo nemoguće!',
    emoji: '🔮',
    category: 'picks',
    rarity: 'legendary',
    condition_type: 'win_rate_80',
    condition_value: 80,
    reward_tokens: 7500,
  },

  // ── TOKENS ───────────────────────────────────────────────────────────────
  {
    key: 'tokens_5k',
    title: 'Prvi koraci',
    description: 'Osvoji ukupno 5.000 tokena',
    emoji: '💵',
    category: 'tokens',
    rarity: 'common',
    condition_type: 'tokens_won',
    condition_value: 5000,
    reward_tokens: 200,
  },
  {
    key: 'tokens_10k',
    title: 'Bogataš',
    description: 'Osvoji ukupno 10.000 tokena',
    emoji: '💰',
    category: 'tokens',
    rarity: 'common',
    condition_type: 'tokens_won',
    condition_value: 10000,
    reward_tokens: 500,
  },
  {
    key: 'tokens_50k',
    title: 'Kapitalista',
    description: 'Osvoji ukupno 50.000 tokena',
    emoji: '🤑',
    category: 'tokens',
    rarity: 'rare',
    condition_type: 'tokens_won',
    condition_value: 50000,
    reward_tokens: 2000,
  },
  {
    key: 'tokens_100k',
    title: 'Milijunaš',
    description: 'Osvoji ukupno 100.000 tokena',
    emoji: '💎',
    category: 'tokens',
    rarity: 'epic',
    condition_type: 'tokens_won',
    condition_value: 100000,
    reward_tokens: 5000,
  },
  {
    key: 'tokens_500k',
    title: 'Tajkun',
    description: 'Osvoji ukupno 500.000 tokena — titan platforme!',
    emoji: '🏦',
    category: 'tokens',
    rarity: 'legendary',
    condition_type: 'tokens_won',
    condition_value: 500000,
    reward_tokens: 25000,
  },

  // ── STREAK ───────────────────────────────────────────────────────────────
  {
    key: 'streak_3',
    title: 'Na tragu',
    description: 'Ostvari 3 točna picka u Daily Streak-u',
    emoji: '🔥',
    category: 'streak',
    rarity: 'common',
    condition_type: 'streak_days',
    condition_value: 3,
    reward_tokens: 300,
  },
  {
    key: 'streak_5',
    title: 'Vrući niz',
    description: 'Pogodi 5 dana zaredom u Daily Streak-u',
    emoji: '🌶️',
    category: 'streak',
    rarity: 'rare',
    condition_type: 'streak_days',
    condition_value: 5,
    reward_tokens: 800,
  },
  {
    key: 'streak_7',
    title: 'Tjedan bez greške',
    description: 'Pogodi svih 7 dana u Daily Streak-u',
    emoji: '⚡',
    category: 'streak',
    rarity: 'epic',
    condition_type: 'streak_days',
    condition_value: 7,
    reward_tokens: 2000,
  },

  // ── PARLAY ───────────────────────────────────────────────────────────────
  {
    key: 'first_parlay',
    title: 'Parlay igrač',
    description: 'Pošalji svoj prvi Parlay',
    emoji: '🎰',
    category: 'picks',
    rarity: 'common',
    condition_type: 'parlay_count',
    condition_value: 1,
    reward_tokens: 150,
  },
  {
    key: 'parlay_10',
    title: 'Kombinator',
    description: 'Pošalji 10 Parlaya',
    emoji: '🧩',
    category: 'picks',
    rarity: 'rare',
    condition_type: 'parlay_count',
    condition_value: 10,
    reward_tokens: 750,
  },
  {
    key: 'parlay_win',
    title: 'Rizičar',
    description: 'Pobijedi u barem jednom Parlayju',
    emoji: '🎲',
    category: 'picks',
    rarity: 'rare',
    condition_type: 'parlay_wins',
    condition_value: 1,
    reward_tokens: 500,
  },
  {
    key: 'parlay_wins_5',
    title: 'Parlay majstor',
    description: 'Pobijedi u 5 Parlaya',
    emoji: '🃏',
    category: 'picks',
    rarity: 'epic',
    condition_type: 'parlay_wins',
    condition_value: 5,
    reward_tokens: 3000,
  },

  // ── DUELI ─────────────────────────────────────────────────────────────────
  {
    key: 'first_duel',
    title: 'Duelist',
    description: 'Sudjeluj u svom prvom dvoboju',
    emoji: '⚔️',
    category: 'social',
    rarity: 'common',
    condition_type: 'duel_count',
    condition_value: 1,
    reward_tokens: 200,
  },
  {
    key: 'duel_win_1',
    title: 'Pobjednik dvoboja',
    description: 'Pobijedi u dvoboju',
    emoji: '🗡️',
    category: 'social',
    rarity: 'rare',
    condition_type: 'duel_wins',
    condition_value: 1,
    reward_tokens: 500,
  },
  {
    key: 'duel_wins_5',
    title: 'Ratnik',
    description: 'Pobijedi u 5 dvoboja',
    emoji: '🛡️',
    category: 'social',
    rarity: 'epic',
    condition_type: 'duel_wins',
    condition_value: 5,
    reward_tokens: 2000,
  },
  {
    key: 'duel_wins_10',
    title: 'Gladijator',
    description: 'Pobijedi u 10 dvoboja — neporažen na areni!',
    emoji: '🏟️',
    category: 'social',
    rarity: 'legendary',
    condition_type: 'duel_wins',
    condition_value: 10,
    reward_tokens: 5000,
  },

  // ── SOCIAL ───────────────────────────────────────────────────────────────
  {
    key: 'first_referral',
    title: 'Ambasador',
    description: 'Pozovi prvog prijatelja',
    emoji: '🤝',
    category: 'social',
    rarity: 'rare',
    condition_type: 'referral_count',
    condition_value: 1,
    reward_tokens: 500,
  },
  {
    key: 'referrals_5',
    title: 'Influencer',
    description: 'Pozovi 5 prijatelja',
    emoji: '📣',
    category: 'social',
    rarity: 'epic',
    condition_type: 'referral_count',
    condition_value: 5,
    reward_tokens: 2500,
  },
  {
    key: 'referrals_10',
    title: 'Recruiter',
    description: 'Pozovi 10 prijatelja na platformu',
    emoji: '🌐',
    category: 'social',
    rarity: 'legendary',
    condition_type: 'referral_count',
    condition_value: 10,
    reward_tokens: 7500,
  },

  // ── SPECIAL ──────────────────────────────────────────────────────────────
  {
    key: 'early_adopter',
    title: 'Early Adopter',
    description: 'Jedan si od prvih igrača na platformi',
    emoji: '🚀',
    category: 'special',
    rarity: 'legendary',
    condition_type: 'special',
    condition_value: 0,
    reward_tokens: 2000,
  },
  {
    key: 'welcome_challenge',
    title: 'Welcome Champion',
    description: 'Završio si Welcome Challenge',
    emoji: '🎊',
    category: 'special',
    rarity: 'rare',
    condition_type: 'special',
    condition_value: 0,
    reward_tokens: 500,
  },
  {
    key: 'week_winner',
    title: 'Pobjednik tjedna',
    description: 'Završio si na vrhu ljestvice za tjedan',
    emoji: '🏅',
    category: 'special',
    rarity: 'epic',
    condition_type: 'special',
    condition_value: 0,
    reward_tokens: 3000,
  },
  {
    key: 'perfect_week',
    title: 'Savršen tjedan',
    description: '7/7 u Daily Streak-u — čisto savršenstvo!',
    emoji: '💯',
    category: 'special',
    rarity: 'legendary',
    condition_type: 'special',
    condition_value: 0,
    reward_tokens: 5000,
  },
  {
    key: 'night_owl',
    title: 'Noćna ptica',
    description: 'Igraš nakon ponoći — pravi nocturnal igrač',
    emoji: '🦉',
    category: 'special',
    rarity: 'common',
    condition_type: 'night_owl',
    condition_value: 0,
    reward_tokens: 150,
  },
  {
    key: 'comeback_kid',
    title: 'Comeback Kid',
    description: 'Pobijedio si nakon 3 uzastopna poraza',
    emoji: '🔄',
    category: 'special',
    rarity: 'rare',
    condition_type: 'comeback',
    condition_value: 3,
    reward_tokens: 750,
  },
];

export const RARITY_CONFIG = {
  common: {
    label: 'Obično',
    color: 'text-slate-400',
    border: 'border-slate-500/30',
    bg: 'bg-slate-500/10',
    glow: '',
  },
  rare: {
    label: 'Rijetko',
    color: 'text-blue-400',
    border: 'border-blue-500/40',
    bg: 'bg-blue-500/10',
    glow: 'shadow-blue-500/20',
  },
  epic: {
    label: 'Epsko',
    color: 'text-purple-400',
    border: 'border-purple-500/40',
    bg: 'bg-purple-500/10',
    glow: 'shadow-purple-500/30',
  },
  legendary: {
    label: 'Legendarno',
    color: 'text-yellow-400',
    border: 'border-yellow-500/50',
    bg: 'bg-yellow-500/10',
    glow: 'shadow-yellow-500/30',
  },
};