// All badge definitions — used for auto-award logic and display
export const BADGE_DEFINITIONS = [
  // --- PICKS ---
  {
    key: 'first_pick',
    title: 'Početnik',
    description: 'Sudjeluj u svom prvom natjecanju',
    emoji: '🎯',
    category: 'picks',
    rarity: 'common',
    condition_type: 'picks_count',
    condition_value: 1,
    reward_tokens: 100,
  },
  {
    key: 'picks_10',
    title: 'Redoviti igrač',
    description: 'Sudjeluj u 10 natjecanja',
    emoji: '🃏',
    category: 'picks',
    rarity: 'common',
    condition_type: 'picks_count',
    condition_value: 10,
    reward_tokens: 250,
  },
  {
    key: 'picks_50',
    title: 'Veteran',
    description: 'Sudjeluj u 50 natjecanja',
    emoji: '⚔️',
    category: 'picks',
    rarity: 'rare',
    condition_type: 'picks_count',
    condition_value: 50,
    reward_tokens: 1000,
  },
  {
    key: 'picks_100',
    title: 'Legenda',
    description: 'Sudjeluj u 100 natjecanja',
    emoji: '👑',
    category: 'picks',
    rarity: 'legendary',
    condition_type: 'picks_count',
    condition_value: 100,
    reward_tokens: 5000,
  },
  // --- WINS ---
  {
    key: 'first_win',
    title: 'Prva pobjeda',
    description: 'Pobijedi u svom prvom natjecanju',
    emoji: '🏆',
    category: 'picks',
    rarity: 'common',
    condition_type: 'wins_count',
    condition_value: 1,
    reward_tokens: 200,
  },
  {
    key: 'wins_10',
    title: 'Pobjednički mentalitet',
    description: 'Osvoji 10 natjecanja',
    emoji: '🥇',
    category: 'picks',
    rarity: 'rare',
    condition_type: 'wins_count',
    condition_value: 10,
    reward_tokens: 500,
  },
  {
    key: 'wins_50',
    title: 'Nepobjedivi',
    description: 'Osvoji 50 natjecanja',
    emoji: '🦁',
    category: 'picks',
    rarity: 'epic',
    condition_type: 'wins_count',
    condition_value: 50,
    reward_tokens: 3000,
  },
  // --- TOKENS ---
  {
    key: 'tokens_10k',
    title: 'Bogataš',
    description: 'Osvoji ukupno 10.000 tokena',
    emoji: '💰',
    category: 'tokens',
    rarity: 'common',
    condition_type: 'tokens_won',
    condition_value: 10000,
    reward_tokens: 500,
  },
  {
    key: 'tokens_100k',
    title: 'Milijunaš',
    description: 'Osvoji ukupno 100.000 tokena',
    emoji: '💎',
    category: 'tokens',
    rarity: 'epic',
    condition_type: 'tokens_won',
    condition_value: 100000,
    reward_tokens: 5000,
  },
  // --- STREAK ---
  {
    key: 'streak_3',
    title: 'Na tragu',
    description: 'Ostvari 3 točna picka u Daily Streak-u',
    emoji: '🔥',
    category: 'streak',
    rarity: 'common',
    condition_type: 'streak_days',
    condition_value: 3,
    reward_tokens: 300,
  },
  {
    key: 'streak_7',
    title: 'Tjedan bez greške',
    description: 'Pogodi svih 7 dana u Daily Streak-u',
    emoji: '⚡',
    category: 'streak',
    rarity: 'epic',
    condition_type: 'streak_days',
    condition_value: 7,
    reward_tokens: 2000,
  },
  // --- PARLAY ---
  {
    key: 'first_parlay',
    title: 'Parlay igrač',
    description: 'Pošalji svoj prvi Parlay',
    emoji: '🎰',
    category: 'picks',
    rarity: 'common',
    condition_type: 'parlay_count',
    condition_value: 1,
    reward_tokens: 150,
  },
  {
    key: 'parlay_10',
    title: 'Kombinator',
    description: 'Pošalji 10 Parlaya',
    emoji: '🧩',
    category: 'picks',
    rarity: 'rare',
    condition_type: 'parlay_count',
    condition_value: 10,
    reward_tokens: 750,
  },
  // --- SOCIAL ---
  {
    key: 'first_referral',
    title: 'Ambasador',
    description: 'Pozovi prvog prijatelja',
    emoji: '🤝',
    category: 'social',
    rarity: 'rare',
    condition_type: 'referral_count',
    condition_value: 1,
    reward_tokens: 500,
  },
  {
    key: 'referrals_5',
    title: 'Influencer',
    description: 'Pozovi 5 prijatelja',
    emoji: '📣',
    category: 'social',
    rarity: 'epic',
    condition_type: 'referral_count',
    condition_value: 5,
    reward_tokens: 2500,
  },
];

export const RARITY_CONFIG = {
  common: {
    label: 'Obično',
    color: 'text-slate-400',
    border: 'border-slate-500/30',
    bg: 'bg-slate-500/10',
    glow: '',
  },
  rare: {
    label: 'Rijetko',
    color: 'text-blue-400',
    border: 'border-blue-500/40',
    bg: 'bg-blue-500/10',
    glow: 'shadow-blue-500/20',
  },
  epic: {
    label: 'Epsko',
    color: 'text-purple-400',
    border: 'border-purple-500/40',
    bg: 'bg-purple-500/10',
    glow: 'shadow-purple-500/30',
  },
  legendary: {
    label: 'Legendarno',
    color: 'text-yellow-400',
    border: 'border-yellow-500/50',
    bg: 'bg-yellow-500/10',
    glow: 'shadow-yellow-500/30',
  },
};