import { Coins, Star, Zap, Crown } from 'lucide-react';

export const TOKEN_PACKAGES = [
  {
    id: 'starter',
    name: 'Starter',
    tokens: 500,
    bonus: 0,
    price: 4.99,
    priceLabel: '€4.99',
    icon: Coins,
    color: 'from-slate-500/20 to-slate-600/5',
    border: 'border-slate-500/20',
    iconColor: 'text-slate-400',
    badge: null,
  },
  {
    id: 'popular',
    name: 'Popular',
    tokens: 1200,
    bonus: 200,
    price: 9.99,
    priceLabel: '€9.99',
    icon: Star,
    color: 'from-primary/20 to-primary/5',
    border: 'border-primary/30',
    iconColor: 'text-primary',
    badge: 'Najpopularnije',
  },
  {
    id: 'pro',
    name: 'Pro',
    tokens: 2500,
    bonus: 500,
    price: 19.99,
    priceLabel: '€19.99',
    icon: Zap,
    color: 'from-fuchsia-500/20 to-fuchsia-600/5',
    border: 'border-fuchsia-500/30',
    iconColor: 'text-fuchsia-400',
    badge: null,
  },
  {
    id: 'elite',
    name: 'Elite',
    tokens: 6000,
    bonus: 1500,
    price: 39.99,
    priceLabel: '€39.99',
    icon: Crown,
    color: 'from-yellow-500/20 to-yellow-600/5',
    border: 'border-yellow-500/30',
    iconColor: 'text-yellow-400',
    badge: 'Najveća vrijednost',
  },
];